version: "3.8"

services:
  ping-pong:
    build: ./
    ports:
      - 8090:8090
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ping-pong:/data/db

volumes:
  ping-pong: 